#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

declare -r threads='16'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

declare -r arg0="$(basename "$0")"

usage() {
    printf '%s [DIR] [URL]...\nArchive redtube videos metadata in json to DIR.\nUrls are taken from recursive spider starting from URL.\n' "$arg0"
}

get_page() {
    local -r name="$(sha256sum <<< "$1"  | cut -d' ' -f1)"
    [ -e "$name" ] && return
    local -r t="$(ucurl "$1" | tr -d '\n\r\t')"
    local -r jn="$(reliq 'script type="application/ld+json" | "%i\n"' <<< "$t")"
    {
    echo "$(jq -r .uploadDate <<< "$jn")" #date
    echo "$(jq -r .duration <<< "$jn")" #duration
    echo "$(jq -r .thumbnailUrl <<< "$jn")" #thumbnail
    echo "$1" #link
    reliq '
        h1 .video_page_title | "%i" / sed "s/<[^>]*>([^<]*)<[^>]*>/\1/" "E" echo "" "\n",
        div .video-infobox-uploader-info; a | "%i" / echo "" "\n",
        span +class="video_view_count" | "%i" / sed "s/ .*//" echo "" "\n",
        div +class="rating_percent js_rating_percent" +data-percent | "%(data-percent)v" / echo "" "\n",
        a .item .video_carousel_item | "%i\t" / echo "" "\n",
        script #tm_pc_player_setup | "%i" / sed "s/.*actionTags: *\"([^\"]*)\",.*/\1/" "E" echo "" "\n",
        div +class="pornstar-name pornstarPopupWrapper"; a +href -class c@[0] | "%(href)v\t" / echo "" "\n"
    ' <<< "$t"
    } | jq -RnMc '
        .["date"]=input |
        .["duration"]=input |
        .["thumbnail"]=input |
        .["link"]=input |
        .["title"]=input |
        .["channel"]=input |
        .["views"]=input |
        .["rating"]=input |
        .["tags"]=(input | split("\t"))[:-1] |
        .["actions"]=(input | split(",") | map(split(":") | {
            ("name"):.[0],
            ("moment"):.[1]
        })) |
        .["stars"]=(input | split("\t"))[:-1]' > "$name"
    reliq 'div #video_related_videos_one; a .video_link href | "https://www.redtube.com%(href)v\n"' <<< "$t" | grep -v '/premium/'
}

if [ "$#" -lt '2' ]
then
    usage >&2
    exit 1
fi

cd "$1" || exit 1
shift

t1="$(mktemp)"
trap 'rm "$t1"' EXIT
while [ "$#" -gt 0 ]
do
    echo "$1" >&2
    get_page "$1"
    shift
done > "$t1"

exit

while :
do
    [ -s "$t1" ] || exit
    j="$(sort -u "$t1")"
    for i in $j
    do
        [ "$(jobs | wc -l)" -gt "$threads" ] && wait %%
        echo "$i" >&2
        get_page "$i" &
    done > "$t1"
    wait
done
